name: ðŸ“¦ Package

on:
  workflow_dispatch:
  push:
    tags: ["v*"]

jobs:
  build-on-platform:
    name: Package on ${{ matrix.version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: windows-2022
          version: win_x64
          pythonArch: x64
        - os: windows-2022
          version: win_x86
          pythonArch: x86
        - os: macos-14
          version: mac_apple
          pythonArch: arm64
        - os: macos-15-intel
          version: mac_intel
          pythonArch: x64
        - os: ubuntu-22.04
          version: ubuntu_x64
          pythonArch: x64

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Classify files, prepare to be packaged
        run: |
          mkdir ./.pkg/code
          mkdir ./.pkg/public
          cp -r ./altfe/ ./.pkg/code/altfe/
          cp -r ./app/ ./.pkg/code/app/
          cp ./main.py ./.pkg/code/
          cp -r ./usr/ ./.pkg/public/usr/
          cp ./app/config/biu_default.yml ./.pkg/public/config.yml
          cp ./LICENSE ./.pkg/public/
          cp ./README.md ./.pkg/public/

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          architecture: ${{ matrix.pythonArch }}

      - name: Setup uv
        uses: astral-sh/setup-uv@v6

      - name: Install Dependencies
        run: |
          uv sync --no-install-project
          uv pip install pyinstaller
      
      - name: Run py-pkger.py
        run: |
          cd ./.pkg/
          uv run --project .. python ./py-pkger.py auto
        
      - name: Compress to ZIP (win)
        if: ${{ contains(matrix.version, 'win') }}
        run: |
          cd ./.pkg/dist/
          mv ./main.exe ./PixivBiu.exe
          Compress-Archive * ../../${{ matrix.version }}.zip
      
      - name: Compress to ZIP (unix-like)
        if: ${{ contains(matrix.version, 'mac') || contains(matrix.version, 'ubuntu') }}
        run: |
          cd ./.pkg/dist/
          mv ./main ./PixivBiu
          zip -r ../../${{ matrix.version }}.zip *
    
      - name: Upload to Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact-${{ matrix.version }}
          path: ./${{ matrix.version }}.zip

  Release:
    needs: [build-on-platform]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Resolve release version
        run: |
          echo "RELEASE_TAG=$(git describe --tags)" >> "$GITHUB_ENV"
      
      - name: Download from Artifact
        uses: actions/download-artifact@v4
        with:
          pattern: my-artifact-*
          merge-multiple: true
      
      - name: Rename
        run: |
          mv ./win_x64.zip ./PixivBiu_${{ env.RELEASE_TAG }}_win_x64.zip
          mv ./win_x86.zip ./PixivBiu_${{ env.RELEASE_TAG }}_win_x86.zip
          mv ./mac_apple.zip ./PixivBiu_${{ env.RELEASE_TAG }}_mac_apple.zip
          mv ./mac_intel.zip ./PixivBiu_${{ env.RELEASE_TAG }}_mac_intel.zip
          mv ./ubuntu_x64.zip ./PixivBiu_${{ env.RELEASE_TAG }}_ubuntu_x64.zip
        
      - name: Release and Done
        uses: ncipollo/release-action@v1
        with:
          artifacts: "PixivBiu_${{ env.RELEASE_TAG }}_win_x64.zip, PixivBiu_${{ env.RELEASE_TAG }}_win_x86.zip, PixivBiu_${{ env.RELEASE_TAG }}_mac_apple.zip, PixivBiu_${{ env.RELEASE_TAG }}_mac_intel.zip, PixivBiu_${{ env.RELEASE_TAG }}_ubuntu_x64.zip"
          tag: ${{ env.RELEASE_TAG }}
          name: ${{ env.RELEASE_TAG }}
          token: ${{ secrets.GITHUB_TOKEN }}
